// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectRng`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fill_bytes`, `next_u32`, `next_u64`

/// Returns base64url(enc || ciphertext), including the AES-GCM tag.
/// AAD is the exact original Connect URL in UTF-8, before URI normalization.
/// No credentials, keys, or URLs should be logged by callers.
Future<String> encryptConnectResponse({
  required String recipientKey,
  required String requestUri,
  required String plaintext,
}) => AppRs.instance.api.crateFfiConnectEncryptConnectResponse(
  recipientKey: recipientKey,
  requestUri: requestUri,
  plaintext: plaintext,
);
